# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

format D 17 2 0
format E 15 2 0
rightstring A0 = "Id"
rightstring B0 = "Fecha"
rightstring C0 = "Respuesta"
rightstring D0 = "TextoRespuesta"
rightstring E0 = "TextoPregunta"
goto A1
