# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

format C 14 2 0
format E 16 2 0
format F 14 2 0
rightstring A0 = "Id"
rightstring B0 = "Titulo"
rightstring C0 = "Descripcion"
rightstring D0 = "Precio"
rightstring E0 = "TipoProductoId"
rightstring F0 = "VendedorId"
goto D1
