# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

format C 14 1 0
rightstring A0 = "Id"
rightstring B0 = "Nombre"
rightstring C0 = "EsComercio"
rightstring D0 = "Email"
rightstring E0 = "Direccion"
rightstring F0 = "Telefono"
goto D1
