# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

format C 15 2 0
format D 13 1 0
format E 13 1 0
rightstring A0 = "Id"
rightstring B0 = "Fecha"
rightstring C0 = "CompradorId"
rightstring D0 = "ProductoId"
rightstring E0 = "VendedorId"
goto D2
